[[redirects]]
from='/'
to='/index.html'
status=200
[[redirects]]
from='/login'
to='https://https://vi-post.herokuapp.com/user/login'
status=200
force=true
[[redirects]]
from='/register'
to='https://https://vi-post.herokuapp.com/user/register'
status=200
force=true
[[redirects]]
from='/post'
to='https://https://vi-post.herokuapp.com/post'
status=200
force=true